# Generated by Django 6.0.6 on 2026-06-24 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=15, unique=True, verbose_name='DNI')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('direccion', models.CharField(max_length=250, verbose_name='Dirección')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, max_length=12, verbose_name='Precio (USD)')),
                ('tipo', models.CharField(choices=[('CASA', 'Casa'), ('DEPA', 'Departamento'), ('TERR', 'Terreno'), ('LOCA', 'Local Comercial')], default='CASA', max_length=4)),
                ('estado', models.CharField(choices=[('DISP', 'Disponible'), ('ALQU', 'Alquilada'), ('VEND', 'Vendida')], default='DISP', max_length=4)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propiedades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='propiedades/')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción de la foto')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='inmobiliaria.propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora de la cita')),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.cliente')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacion', models.CharField(choices=[('VENTA', 'Venta'), ('ALQUILER', 'Alquiler')], max_length=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('monto_final', models.DecimalField(decimal_places=2, max_digits=12)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inmobiliaria.cliente')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inmobiliaria.propiedad')),
            ],
        ),
    ]
